"""Add email confirmation

Revision ID: cae0c3896e4a
Revises: e81e6a49b002
Create Date: 2020-02-22 15:51:23.308470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae0c3896e4a'
down_revision = 'e81e6a49b002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed_on')
    op.drop_column('user', 'email_confirmed')
    op.drop_column('user', 'email_confirmation_sent_on')
    # ### end Alembic commands ###
